
/user/info:
  get:
        tags:
          - User
        summary: 유저 정보 조회
        responses:
          '200':
            description: 유저 정보 성공!
            schema:
              type: object
              properties:
                status:
                  type: integer
                  example: 200
                isSuccess:
                  type: boolean
                  example: true
                code:
                  type: integer
                  example: 2000
                message:
                  type: string
                  example: "success!"
                data:
                  type: object
                  example: {
                    "id" : 0000
                  }
                  
          '400':
            description: 잘못된 요청
            schema:
              type: object
              properties:
                status:
                  type: integer
                  example: 400
                isSuccess:
                  type: boolean
                  example: false
                code:
                  type: integer
                  example: COMMON001
                message:
                  type: string
                  example: 잘못된 요청입니다

          '500':
            description: 서버 에러
            schema:
              type: object
              properties:
                status:
                  type: integer
                  example: 500
                isSuccess:
                  type: boolean
                  example: false
                code:
                  type: integer
                  example: COMMON000
                message:
                  type: string
                  example: 서버 에러, 관리자에게 문의 바랍니다.

/user/signin:
    
    put:
      tags:
        - User
      summary: 회원가입
      parameters:
      - name: signin
        in: body
        required: true
        schema:
          properties:
            id:
              type: integer
              description: 유저 아이디
              example: 11
           
            nickname:
              type: string
              description: 유저 별명
              example: joon
            school:
              type: string
              description: 유저 학교
              example: 명지대학교
            phone:
              type: string
              description: 전화 번호
              example: 010-0000-0000
            
      responses:
        '200':
          description: 회원 가입 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  "id" : 0000
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.

